TRAIN:
  MAX_ITER: 200000
  LOG_OUTPUT_PATH: "log/R101-FPN_3x_MAXiter200000"
  CONFIG_FILE_PATH: "detectron2/configs/COCO-InstanceSegmentation/mask_rcnn_R_101_FPN_3x.yaml"
  MODEL_WEIGHTS_PATH: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
TEST:
  MODEL_WEIGHTS_PATH_TEST: "log/R101-FPN_3x_MAXiter200000/model_final.pth"